
machine:
  services:
    - docker

dependencies:
  post:
    - docker build -t 923903436004.dkr.ecr.us-east-1.amazonaws.com/mike-repo:$CIRCLE_SHA1 .

test:
  post:
    - docker run -d -p 8080:8080 --name sample-go-webapp 923903436004.dkr.ecr.us-east-1.amazonaws.com/mike-repo:$CIRCLE_SHA1; sleep 10
    - curl --retry 10 --retry-delay 5 localhost:8080 | grep "Hello World!"

deployment:
  prod:
    branch: master
    commands:
      - ./deploy.sh
